#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalutinisAtsiskaitymas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UserDataBase")]
	public partial class KonverterisDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUserInfo(UserInfo instance);
    partial void UpdateUserInfo(UserInfo instance);
    partial void DeleteUserInfo(UserInfo instance);
    partial void InsertAtmintiesScore(AtmintiesScore instance);
    partial void UpdateAtmintiesScore(AtmintiesScore instance);
    partial void DeleteAtmintiesScore(AtmintiesScore instance);
    partial void InsertPlatformerScore(PlatformerScore instance);
    partial void UpdatePlatformerScore(PlatformerScore instance);
    partial void DeletePlatformerScore(PlatformerScore instance);
    #endregion
		
		public KonverterisDataContext() : 
				base(global::GalutinisAtsiskaitymas.Properties.Settings.Default.UserDataBaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KonverterisDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KonverterisDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KonverterisDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KonverterisDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserInfo> UserInfos
		{
			get
			{
				return this.GetTable<UserInfo>();
			}
		}
		
		public System.Data.Linq.Table<AtmintiesScore> AtmintiesScores
		{
			get
			{
				return this.GetTable<AtmintiesScore>();
			}
		}
		
		public System.Data.Linq.Table<PlatformerScore> PlatformerScores
		{
			get
			{
				return this.GetTable<PlatformerScore>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserInfo")]
	public partial class UserInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _UserName;
		
		private string _Email;
		
		private System.DateTime _BirthDate;
		
		private string _Hash;
		
		private string _Salt;
		
		private EntitySet<AtmintiesScore> _AtmintiesScores;
		
		private EntitySet<PlatformerScore> _PlatformerScores;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnBirthDateChanging(System.DateTime value);
    partial void OnBirthDateChanged();
    partial void OnHashChanging(string value);
    partial void OnHashChanged();
    partial void OnSaltChanging(string value);
    partial void OnSaltChanged();
    #endregion
		
		public UserInfo()
		{
			this._AtmintiesScores = new EntitySet<AtmintiesScore>(new Action<AtmintiesScore>(this.attach_AtmintiesScores), new Action<AtmintiesScore>(this.detach_AtmintiesScores));
			this._PlatformerScores = new EntitySet<PlatformerScore>(new Action<PlatformerScore>(this.attach_PlatformerScores), new Action<PlatformerScore>(this.detach_PlatformerScores));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="Date NOT NULL")]
		public System.DateTime BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this.OnBirthDateChanging(value);
					this.SendPropertyChanging();
					this._BirthDate = value;
					this.SendPropertyChanged("BirthDate");
					this.OnBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hash", DbType="NVarChar(MAX)")]
		public string Hash
		{
			get
			{
				return this._Hash;
			}
			set
			{
				if ((this._Hash != value))
				{
					this.OnHashChanging(value);
					this.SendPropertyChanging();
					this._Hash = value;
					this.SendPropertyChanged("Hash");
					this.OnHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salt", DbType="NVarChar(MAX)")]
		public string Salt
		{
			get
			{
				return this._Salt;
			}
			set
			{
				if ((this._Salt != value))
				{
					this.OnSaltChanging(value);
					this.SendPropertyChanging();
					this._Salt = value;
					this.SendPropertyChanged("Salt");
					this.OnSaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserInfo_AtmintiesScore", Storage="_AtmintiesScores", ThisKey="Id", OtherKey="VartotojoID")]
		public EntitySet<AtmintiesScore> AtmintiesScores
		{
			get
			{
				return this._AtmintiesScores;
			}
			set
			{
				this._AtmintiesScores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserInfo_PlatformerScore", Storage="_PlatformerScores", ThisKey="Id", OtherKey="VartotojoID")]
		public EntitySet<PlatformerScore> PlatformerScores
		{
			get
			{
				return this._PlatformerScores;
			}
			set
			{
				this._PlatformerScores.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AtmintiesScores(AtmintiesScore entity)
		{
			this.SendPropertyChanging();
			entity.UserInfo = this;
		}
		
		private void detach_AtmintiesScores(AtmintiesScore entity)
		{
			this.SendPropertyChanging();
			entity.UserInfo = null;
		}
		
		private void attach_PlatformerScores(PlatformerScore entity)
		{
			this.SendPropertyChanging();
			entity.UserInfo = this;
		}
		
		private void detach_PlatformerScores(PlatformerScore entity)
		{
			this.SendPropertyChanging();
			entity.UserInfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AtmintiesScore")]
	public partial class AtmintiesScore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _VartotojoID;
		
		private string _Laikas;
		
		private EntityRef<UserInfo> _UserInfo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnVartotojoIDChanging(int value);
    partial void OnVartotojoIDChanged();
    partial void OnLaikasChanging(string value);
    partial void OnLaikasChanged();
    #endregion
		
		public AtmintiesScore()
		{
			this._UserInfo = default(EntityRef<UserInfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VartotojoID", DbType="Int NOT NULL")]
		public int VartotojoID
		{
			get
			{
				return this._VartotojoID;
			}
			set
			{
				if ((this._VartotojoID != value))
				{
					if (this._UserInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVartotojoIDChanging(value);
					this.SendPropertyChanging();
					this._VartotojoID = value;
					this.SendPropertyChanged("VartotojoID");
					this.OnVartotojoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Laikas", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Laikas
		{
			get
			{
				return this._Laikas;
			}
			set
			{
				if ((this._Laikas != value))
				{
					this.OnLaikasChanging(value);
					this.SendPropertyChanging();
					this._Laikas = value;
					this.SendPropertyChanged("Laikas");
					this.OnLaikasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserInfo_AtmintiesScore", Storage="_UserInfo", ThisKey="VartotojoID", OtherKey="Id", IsForeignKey=true)]
		public UserInfo UserInfo
		{
			get
			{
				return this._UserInfo.Entity;
			}
			set
			{
				UserInfo previousValue = this._UserInfo.Entity;
				if (((previousValue != value) 
							|| (this._UserInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserInfo.Entity = null;
						previousValue.AtmintiesScores.Remove(this);
					}
					this._UserInfo.Entity = value;
					if ((value != null))
					{
						value.AtmintiesScores.Add(this);
						this._VartotojoID = value.Id;
					}
					else
					{
						this._VartotojoID = default(int);
					}
					this.SendPropertyChanged("UserInfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PlatformerScore")]
	public partial class PlatformerScore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _VartotojoID;
		
		private string _Laikas;
		
		private int _Gyvybes;
		
		private EntityRef<UserInfo> _UserInfo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnVartotojoIDChanging(int value);
    partial void OnVartotojoIDChanged();
    partial void OnLaikasChanging(string value);
    partial void OnLaikasChanged();
    partial void OnGyvybesChanging(int value);
    partial void OnGyvybesChanged();
    #endregion
		
		public PlatformerScore()
		{
			this._UserInfo = default(EntityRef<UserInfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VartotojoID", DbType="Int NOT NULL")]
		public int VartotojoID
		{
			get
			{
				return this._VartotojoID;
			}
			set
			{
				if ((this._VartotojoID != value))
				{
					if (this._UserInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVartotojoIDChanging(value);
					this.SendPropertyChanging();
					this._VartotojoID = value;
					this.SendPropertyChanged("VartotojoID");
					this.OnVartotojoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Laikas", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Laikas
		{
			get
			{
				return this._Laikas;
			}
			set
			{
				if ((this._Laikas != value))
				{
					this.OnLaikasChanging(value);
					this.SendPropertyChanging();
					this._Laikas = value;
					this.SendPropertyChanged("Laikas");
					this.OnLaikasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gyvybes", DbType="Int NOT NULL")]
		public int Gyvybes
		{
			get
			{
				return this._Gyvybes;
			}
			set
			{
				if ((this._Gyvybes != value))
				{
					this.OnGyvybesChanging(value);
					this.SendPropertyChanging();
					this._Gyvybes = value;
					this.SendPropertyChanged("Gyvybes");
					this.OnGyvybesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserInfo_PlatformerScore", Storage="_UserInfo", ThisKey="VartotojoID", OtherKey="Id", IsForeignKey=true)]
		public UserInfo UserInfo
		{
			get
			{
				return this._UserInfo.Entity;
			}
			set
			{
				UserInfo previousValue = this._UserInfo.Entity;
				if (((previousValue != value) 
							|| (this._UserInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserInfo.Entity = null;
						previousValue.PlatformerScores.Remove(this);
					}
					this._UserInfo.Entity = value;
					if ((value != null))
					{
						value.PlatformerScores.Add(this);
						this._VartotojoID = value.Id;
					}
					else
					{
						this._VartotojoID = default(int);
					}
					this.SendPropertyChanged("UserInfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
